// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { NextApiHandler, ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type PagesPageConfig = {
  default: React.ComponentType<any> | ((props: any) => React.ReactNode | Promise<React.ReactNode> | never | void)
  getStaticProps?: (context: any) => Promise<any> | any
  getStaticPaths?: (context: any) => Promise<any> | any
  getServerSideProps?: (context: any) => Promise<any> | any
  getInitialProps?: (context: any) => Promise<any> | any
  /**
   * Segment configuration for legacy Pages Router pages.
   * Validated at build-time by parsePagesSegmentConfig.
   */
  config?: {
    amp?: boolean | 'hybrid' | string // necessary for JS
    maxDuration?: number
    runtime?: 'edge' | 'experimental-edge' | 'nodejs' | string // necessary unless config is exported as const
    regions?: string[]
  }
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}

type ApiRouteConfig = {
  default: (req: any, res: any) => ReturnType<NextApiHandler>
  config?: {
    api?: {
      bodyParser?: boolean | { sizeLimit?: string }
      responseLimit?: string | number | boolean
      externalResolver?: boolean
    }
    runtime?: 'edge' | 'experimental-edge' | 'nodejs' | string // necessary unless config is exported as const
    maxDuration?: number
  }
}


// Validate ../../src/app/about-us/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about-us">> = Specific
  const handler = {} as typeof import("../../src/app/about-us/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/add-package/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/add-package">> = Specific
  const handler = {} as typeof import("../../src/app/admin/add-package/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/api-keys/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/api-keys">> = Specific
  const handler = {} as typeof import("../../src/app/admin/api-keys/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/bills/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/bills">> = Specific
  const handler = {} as typeof import("../../src/app/admin/bills/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/broadcasts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/broadcasts">> = Specific
  const handler = {} as typeof import("../../src/app/admin/broadcasts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/currencies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/currencies">> = Specific
  const handler = {} as typeof import("../../src/app/admin/currencies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/customers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/customers">> = Specific
  const handler = {} as typeof import("../../src/app/admin/customers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/documentation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/documentation">> = Specific
  const handler = {} as typeof import("../../src/app/admin/documentation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/invoices/generator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/invoices/generator">> = Specific
  const handler = {} as typeof import("../../src/app/admin/invoices/generator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/invoices/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/invoices">> = Specific
  const handler = {} as typeof import("../../src/app/admin/invoices/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/packages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/packages">> = Specific
  const handler = {} as typeof import("../../src/app/admin/packages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/pos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/pos">> = Specific
  const handler = {} as typeof import("../../src/app/admin/pos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/pre-alerts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/pre-alerts">> = Specific
  const handler = {} as typeof import("../../src/app/admin/pre-alerts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/profile">> = Specific
  const handler = {} as typeof import("../../src/app/admin/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/rate-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/rate-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/admin/rate-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/receivals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/receivals">> = Specific
  const handler = {} as typeof import("../../src/app/admin/receivals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/reporting/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/reporting">> = Specific
  const handler = {} as typeof import("../../src/app/admin/reporting/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/reports">> = Specific
  const handler = {} as typeof import("../../src/app/admin/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings">> = Specific
  const handler = {} as typeof import("../../src/app/admin/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/shipments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/shipments">> = Specific
  const handler = {} as typeof import("../../src/app/admin/shipments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/staff/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/staff">> = Specific
  const handler = {} as typeof import("../../src/app/admin/staff/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/status/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/status">> = Specific
  const handler = {} as typeof import("../../src/app/admin/status/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/transactions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/transactions">> = Specific
  const handler = {} as typeof import("../../src/app/admin/transactions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/unknown-packages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/unknown-packages">> = Specific
  const handler = {} as typeof import("../../src/app/admin/unknown-packages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/warehouse/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/warehouse">> = Specific
  const handler = {} as typeof import("../../src/app/admin/warehouse/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../src/app/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/customer/addresses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer/addresses">> = Specific
  const handler = {} as typeof import("../../src/app/customer/addresses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/customer/archives/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer/archives">> = Specific
  const handler = {} as typeof import("../../src/app/customer/archives/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/customer/bills/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer/bills">> = Specific
  const handler = {} as typeof import("../../src/app/customer/bills/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/customer/checkout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer/checkout">> = Specific
  const handler = {} as typeof import("../../src/app/customer/checkout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/customer/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer/contact">> = Specific
  const handler = {} as typeof import("../../src/app/customer/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/customer/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/customer/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/customer/faq/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer/faq">> = Specific
  const handler = {} as typeof import("../../src/app/customer/faq/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/customer/invoice-upload/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer/invoice-upload">> = Specific
  const handler = {} as typeof import("../../src/app/customer/invoice-upload/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/customer/messages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer/messages">> = Specific
  const handler = {} as typeof import("../../src/app/customer/messages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/customer/packages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer/packages">> = Specific
  const handler = {} as typeof import("../../src/app/customer/packages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/customer/payments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer/payments">> = Specific
  const handler = {} as typeof import("../../src/app/customer/payments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/customer/pre-alerts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer/pre-alerts">> = Specific
  const handler = {} as typeof import("../../src/app/customer/pre-alerts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/customer/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer/profile">> = Specific
  const handler = {} as typeof import("../../src/app/customer/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/customer/shipping-addresses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer/shipping-addresses">> = Specific
  const handler = {} as typeof import("../../src/app/customer/shipping-addresses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/customer/shipping-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer/shipping-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/customer/shipping-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/customer/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer/support">> = Specific
  const handler = {} as typeof import("../../src/app/customer/support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/customs-policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customs-policy">> = Specific
  const handler = {} as typeof import("../../src/app/customs-policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../src/app/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/password-reset/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/password-reset">> = Specific
  const handler = {} as typeof import("../../src/app/password-reset/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/rates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rates">> = Specific
  const handler = {} as typeof import("../../src/app/rates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../src/app/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/search/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/search">> = Specific
  const handler = {} as typeof import("../../src/app/search/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services">> = Specific
  const handler = {} as typeof import("../../src/app/services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/track/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/track">> = Specific
  const handler = {} as typeof import("../../src/app/track/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tracking/[trackingNumber]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tracking/[trackingNumber]">> = Specific
  const handler = {} as typeof import("../../src/app/tracking/[trackingNumber]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tracking/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tracking">> = Specific
  const handler = {} as typeof import("../../src/app/tracking/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/warehouse/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/warehouse/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/warehouse/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/warehouse/account/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/warehouse/account">> = Specific
  const handler = {} as typeof import("../../src/app/warehouse/account/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/warehouse/add-package/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/warehouse/add-package">> = Specific
  const handler = {} as typeof import("../../src/app/warehouse/add-package/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/warehouse/addresses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/warehouse/addresses">> = Specific
  const handler = {} as typeof import("../../src/app/warehouse/addresses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/warehouse/bulk-upload/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/warehouse/bulk-upload">> = Specific
  const handler = {} as typeof import("../../src/app/warehouse/bulk-upload/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/warehouse/customers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/warehouse/customers">> = Specific
  const handler = {} as typeof import("../../src/app/warehouse/customers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/warehouse/integrations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/warehouse/integrations">> = Specific
  const handler = {} as typeof import("../../src/app/warehouse/integrations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/warehouse/inventory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/warehouse/inventory">> = Specific
  const handler = {} as typeof import("../../src/app/warehouse/inventory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/warehouse/manifests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/warehouse/manifests">> = Specific
  const handler = {} as typeof import("../../src/app/warehouse/manifests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/warehouse/messages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/warehouse/messages">> = Specific
  const handler = {} as typeof import("../../src/app/warehouse/messages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/warehouse/packages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/warehouse/packages">> = Specific
  const handler = {} as typeof import("../../src/app/warehouse/packages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/warehouse/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/warehouse">> = Specific
  const handler = {} as typeof import("../../src/app/warehouse/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/warehouse/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/warehouse/reports">> = Specific
  const handler = {} as typeof import("../../src/app/warehouse/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/warehouse/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/warehouse/settings">> = Specific
  const handler = {} as typeof import("../../src/app/warehouse/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/warehouse/staff/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/warehouse/staff">> = Specific
  const handler = {} as typeof import("../../src/app/warehouse/staff/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/warehouse/update-status/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/warehouse/update-status">> = Specific
  const handler = {} as typeof import("../../src/app/warehouse/update-status/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/analytics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/analytics">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/analytics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/api-keys/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/api-keys/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/api-keys/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/api-keys/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/api-keys">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/api-keys/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/audit-logs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/audit-logs">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/audit-logs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/bills/pay/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/bills/pay">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/bills/pay/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/bills/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/bills">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/bills/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/broadcast-messages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/broadcast-messages">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/broadcast-messages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/currencies/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/currencies">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/currencies/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/customers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/customers">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/customers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/dashboard/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/dashboard/stats">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/dashboard/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/docs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/docs">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/docs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/integrations/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/integrations/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/integrations/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/integrations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/integrations">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/integrations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/invoices/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/invoices/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/invoices/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/invoices/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/invoices/generate">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/invoices/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/invoices/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/invoices">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/invoices/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/kcd-key/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/kcd-key">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/kcd-key/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/logs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/logs">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/logs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/messages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/messages">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/messages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/packages/[packageId]/invoice/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/packages/[packageId]/invoice">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/packages/[packageId]/invoice/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/packages/[packageId]/invoices/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/packages/[packageId]/invoices">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/packages/[packageId]/invoices/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/packages/[packageId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/packages/[packageId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/packages/[packageId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/packages/bulk-import/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/packages/bulk-import">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/packages/bulk-import/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/packages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/packages">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/packages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/packages/unknown/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/packages/unknown">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/packages/unknown/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/paypal/capture/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/paypal/capture">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/paypal/capture/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/paypal/create-order/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/paypal/create-order">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/paypal/create-order/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/paypal/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/paypal/sync">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/paypal/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/pos/transactions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/pos/transactions">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/pos/transactions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/pre-alerts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/pre-alerts">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/pre-alerts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/pricing-rules/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/pricing-rules">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/pricing-rules/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/profile/password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/profile/password">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/profile/password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/profile">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/receivals/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/receivals">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/receivals/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/reports/[type]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/reports/[type]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/reports/[type]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/reports/dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/reports/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/reports/dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/reports/summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/reports/summary">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/reports/summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/seed-inventory/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/seed-inventory">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/seed-inventory/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/services/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/services">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/services/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/settings">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/settings/shipping-charges/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/settings/shipping-charges">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/settings/shipping-charges/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/shipments/manifests/update/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/shipments/manifests/update">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/shipments/manifests/update/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/staff/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/staff">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/staff/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/status">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/transactions/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/transactions/export">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/transactions/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/transactions/refund/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/transactions/refund">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/transactions/refund/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/transactions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/transactions">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/transactions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/warehouses/[id]/shipping-addresses/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/warehouses/[id]/shipping-addresses">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/warehouses/[id]/shipping-addresses/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/forgot-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/forgot-password">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/forgot-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/me">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/password/request/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/password/request">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/password/request/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/password/reset/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/password/reset">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/password/reset/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/password/verify-otp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/password/verify-otp">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/password/verify-otp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/register/[userId]/details/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/register/[userId]/details">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/register/[userId]/details/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/register">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/resend-verification/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/resend-verification">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/resend-verification/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/reset-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/reset-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/verify">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/check-staff/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/check-staff">> = Specific
  const handler = {} as typeof import("../../src/app/api/check-staff/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/create-admin/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/create-admin">> = Specific
  const handler = {} as typeof import("../../src/app/api/create-admin/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/currencies/convert/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/currencies/convert">> = Specific
  const handler = {} as typeof import("../../src/app/api/currencies/convert/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/currencies/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/currencies">> = Specific
  const handler = {} as typeof import("../../src/app/api/currencies/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/customer/addresses/[id]/default/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/customer/addresses/[id]/default">> = Specific
  const handler = {} as typeof import("../../src/app/api/customer/addresses/[id]/default/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/customer/addresses/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/customer/addresses/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/customer/addresses/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/customer/addresses/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/customer/addresses">> = Specific
  const handler = {} as typeof import("../../src/app/api/customer/addresses/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/customer/archives/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/customer/archives">> = Specific
  const handler = {} as typeof import("../../src/app/api/customer/archives/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/customer/bills/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/customer/bills">> = Specific
  const handler = {} as typeof import("../../src/app/api/customer/bills/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/customer/faq/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/customer/faq">> = Specific
  const handler = {} as typeof import("../../src/app/api/customer/faq/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/customer/invoice-upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/customer/invoice-upload">> = Specific
  const handler = {} as typeof import("../../src/app/api/customer/invoice-upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/customer/invoices/[invoiceNumber]/download/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/customer/invoices/[invoiceNumber]/download">> = Specific
  const handler = {} as typeof import("../../src/app/api/customer/invoices/[invoiceNumber]/download/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/customer/messages/dismiss-broadcast/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/customer/messages/dismiss-broadcast">> = Specific
  const handler = {} as typeof import("../../src/app/api/customer/messages/dismiss-broadcast/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/customer/messages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/customer/messages">> = Specific
  const handler = {} as typeof import("../../src/app/api/customer/messages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/customer/packages/[id]/invoice/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/customer/packages/[id]/invoice">> = Specific
  const handler = {} as typeof import("../../src/app/api/customer/packages/[id]/invoice/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/customer/packages/pre-alert/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/customer/packages/pre-alert">> = Specific
  const handler = {} as typeof import("../../src/app/api/customer/packages/pre-alert/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/customer/packages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/customer/packages">> = Specific
  const handler = {} as typeof import("../../src/app/api/customer/packages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/customer/packages/track/[trackingNumber]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/customer/packages/track/[trackingNumber]">> = Specific
  const handler = {} as typeof import("../../src/app/api/customer/packages/track/[trackingNumber]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/customer/payments/apply/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/customer/payments/apply">> = Specific
  const handler = {} as typeof import("../../src/app/api/customer/payments/apply/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/customer/payments/capture-paypal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/customer/payments/capture-paypal">> = Specific
  const handler = {} as typeof import("../../src/app/api/customer/payments/capture-paypal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/customer/payments/create-paypal-order/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/customer/payments/create-paypal-order">> = Specific
  const handler = {} as typeof import("../../src/app/api/customer/payments/create-paypal-order/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/customer/payments/process-bulk/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/customer/payments/process-bulk">> = Specific
  const handler = {} as typeof import("../../src/app/api/customer/payments/process-bulk/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/customer/payments/process/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/customer/payments/process">> = Specific
  const handler = {} as typeof import("../../src/app/api/customer/payments/process/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/customer/payments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/customer/payments">> = Specific
  const handler = {} as typeof import("../../src/app/api/customer/payments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/customer/pre-alerts/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/customer/pre-alerts/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/customer/pre-alerts/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/customer/pre-alerts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/customer/pre-alerts">> = Specific
  const handler = {} as typeof import("../../src/app/api/customer/pre-alerts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/customer/profile/password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/customer/profile/password">> = Specific
  const handler = {} as typeof import("../../src/app/api/customer/profile/password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/customer/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/customer/profile">> = Specific
  const handler = {} as typeof import("../../src/app/api/customer/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/customer/shipping-addresses/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/customer/shipping-addresses">> = Specific
  const handler = {} as typeof import("../../src/app/api/customer/shipping-addresses/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/customer/shipping/calculate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/customer/shipping/calculate">> = Specific
  const handler = {} as typeof import("../../src/app/api/customer/shipping/calculate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/customer/support/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/customer/support">> = Specific
  const handler = {} as typeof import("../../src/app/api/customer/support/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/customers/[userCode]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/customers/[userCode]">> = Specific
  const handler = {} as typeof import("../../src/app/api/customers/[userCode]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/customers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/customers">> = Specific
  const handler = {} as typeof import("../../src/app/api/customers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dev/create-admin/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dev/create-admin">> = Specific
  const handler = {} as typeof import("../../src/app/api/dev/create-admin/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dev/seed-admin/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dev/seed-admin">> = Specific
  const handler = {} as typeof import("../../src/app/api/dev/seed-admin/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dev/seed-customer/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dev/seed-customer">> = Specific
  const handler = {} as typeof import("../../src/app/api/dev/seed-customer/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dev/seed-packages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dev/seed-packages">> = Specific
  const handler = {} as typeof import("../../src/app/api/dev/seed-packages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../src/app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/init/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/init">> = Specific
  const handler = {} as typeof import("../../src/app/api/init/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/packages/[id]/invoice/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/packages/[id]/invoice">> = Specific
  const handler = {} as typeof import("../../src/app/api/packages/[id]/invoice/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/packages/[id]/payment/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/packages/[id]/payment">> = Specific
  const handler = {} as typeof import("../../src/app/api/packages/[id]/payment/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/search">> = Specific
  const handler = {} as typeof import("../../src/app/api/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/support/contact/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/support/contact">> = Specific
  const handler = {} as typeof import("../../src/app/api/support/contact/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tasoko/add-package/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tasoko/add-package">> = Specific
  const handler = {} as typeof import("../../src/app/api/tasoko/add-package/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tasoko/delete-package/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tasoko/delete-package">> = Specific
  const handler = {} as typeof import("../../src/app/api/tasoko/delete-package/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tasoko/get-customers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tasoko/get-customers">> = Specific
  const handler = {} as typeof import("../../src/app/api/tasoko/get-customers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tasoko/update-manifest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tasoko/update-manifest">> = Specific
  const handler = {} as typeof import("../../src/app/api/tasoko/update-manifest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tasoko/update-package/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tasoko/update-package">> = Specific
  const handler = {} as typeof import("../../src/app/api/tasoko/update-package/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tracking/[trackingNumber]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tracking/[trackingNumber]">> = Specific
  const handler = {} as typeof import("../../src/app/api/tracking/[trackingNumber]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/warehouse/account/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/warehouse/account">> = Specific
  const handler = {} as typeof import("../../src/app/api/warehouse/account/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/warehouse/addpackage/subdir/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/warehouse/addpackage/subdir">> = Specific
  const handler = {} as typeof import("../../src/app/api/warehouse/addpackage/subdir/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/warehouse/addresses/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/warehouse/addresses/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/warehouse/addresses/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/warehouse/addresses/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/warehouse/addresses">> = Specific
  const handler = {} as typeof import("../../src/app/api/warehouse/addresses/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/warehouse/analytics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/warehouse/analytics">> = Specific
  const handler = {} as typeof import("../../src/app/api/warehouse/analytics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/warehouse/customers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/warehouse/customers">> = Specific
  const handler = {} as typeof import("../../src/app/api/warehouse/customers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/warehouse/deletepackage/subdir/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/warehouse/deletepackage/subdir">> = Specific
  const handler = {} as typeof import("../../src/app/api/warehouse/deletepackage/subdir/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/warehouse/editpackage/subdir/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/warehouse/editpackage/subdir">> = Specific
  const handler = {} as typeof import("../../src/app/api/warehouse/editpackage/subdir/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/warehouse/getpackages/subdir/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/warehouse/getpackages/subdir">> = Specific
  const handler = {} as typeof import("../../src/app/api/warehouse/getpackages/subdir/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/warehouse/inventory/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/warehouse/inventory/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/warehouse/inventory/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/warehouse/inventory/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/warehouse/inventory">> = Specific
  const handler = {} as typeof import("../../src/app/api/warehouse/inventory/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/warehouse/manifests/[id]/complete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/warehouse/manifests/[id]/complete">> = Specific
  const handler = {} as typeof import("../../src/app/api/warehouse/manifests/[id]/complete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/warehouse/manifests/[id]/packages/[packageId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/warehouse/manifests/[id]/packages/[packageId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/warehouse/manifests/[id]/packages/[packageId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/warehouse/manifests/[id]/packages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/warehouse/manifests/[id]/packages">> = Specific
  const handler = {} as typeof import("../../src/app/api/warehouse/manifests/[id]/packages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/warehouse/manifests/[id]/start/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/warehouse/manifests/[id]/start">> = Specific
  const handler = {} as typeof import("../../src/app/api/warehouse/manifests/[id]/start/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/warehouse/manifests/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/warehouse/manifests">> = Specific
  const handler = {} as typeof import("../../src/app/api/warehouse/manifests/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/warehouse/manifests/update/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/warehouse/manifests/update">> = Specific
  const handler = {} as typeof import("../../src/app/api/warehouse/manifests/update/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/warehouse/messages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/warehouse/messages">> = Specific
  const handler = {} as typeof import("../../src/app/api/warehouse/messages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/warehouse/packages/[id]/link/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/warehouse/packages/[id]/link">> = Specific
  const handler = {} as typeof import("../../src/app/api/warehouse/packages/[id]/link/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/warehouse/packages/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/warehouse/packages/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/warehouse/packages/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/warehouse/packages/add/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/warehouse/packages/add">> = Specific
  const handler = {} as typeof import("../../src/app/api/warehouse/packages/add/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/warehouse/packages/bulk-upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/warehouse/packages/bulk-upload">> = Specific
  const handler = {} as typeof import("../../src/app/api/warehouse/packages/bulk-upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/warehouse/packages/delete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/warehouse/packages/delete">> = Specific
  const handler = {} as typeof import("../../src/app/api/warehouse/packages/delete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/warehouse/packages/exist/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/warehouse/packages/exist">> = Specific
  const handler = {} as typeof import("../../src/app/api/warehouse/packages/exist/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/warehouse/packages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/warehouse/packages">> = Specific
  const handler = {} as typeof import("../../src/app/api/warehouse/packages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/warehouse/packages/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/warehouse/packages/search">> = Specific
  const handler = {} as typeof import("../../src/app/api/warehouse/packages/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/warehouse/packages/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/warehouse/packages/stats">> = Specific
  const handler = {} as typeof import("../../src/app/api/warehouse/packages/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/warehouse/packages/unknown/count/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/warehouse/packages/unknown/count">> = Specific
  const handler = {} as typeof import("../../src/app/api/warehouse/packages/unknown/count/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/warehouse/packages/unknown/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/warehouse/packages/unknown">> = Specific
  const handler = {} as typeof import("../../src/app/api/warehouse/packages/unknown/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/warehouse/packages/update-status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/warehouse/packages/update-status">> = Specific
  const handler = {} as typeof import("../../src/app/api/warehouse/packages/update-status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/warehouse/pullcustomer/subdir/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/warehouse/pullcustomer/subdir">> = Specific
  const handler = {} as typeof import("../../src/app/api/warehouse/pullcustomer/subdir/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/warehouse/rate-calculator/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/warehouse/rate-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/api/warehouse/rate-calculator/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/warehouse/reports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/warehouse/reports">> = Specific
  const handler = {} as typeof import("../../src/app/api/warehouse/reports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/warehouse/scan/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/warehouse/scan">> = Specific
  const handler = {} as typeof import("../../src/app/api/warehouse/scan/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/warehouse/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/warehouse/search">> = Specific
  const handler = {} as typeof import("../../src/app/api/warehouse/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/warehouse/settings/password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/warehouse/settings/password">> = Specific
  const handler = {} as typeof import("../../src/app/api/warehouse/settings/password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/warehouse/settings/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/warehouse/settings/profile">> = Specific
  const handler = {} as typeof import("../../src/app/api/warehouse/settings/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/warehouse/staff/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/warehouse/staff/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/warehouse/staff/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/warehouse/staff/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/warehouse/staff">> = Specific
  const handler = {} as typeof import("../../src/app/api/warehouse/staff/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/warehouse/updatemanifest/subdir/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/warehouse/updatemanifest/subdir">> = Specific
  const handler = {} as typeof import("../../src/app/api/warehouse/updatemanifest/subdir/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/pages/_app.tsx
{
  type __IsExpected<Specific extends PagesPageConfig> = Specific
  const handler = {} as typeof import("../../src/pages/_app.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/pages/api/admin/protected-route.ts
{
  type __IsExpected<Specific extends ApiRouteConfig> = Specific
  const handler = {} as typeof import("../../src/pages/api/admin/protected-route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/pages/api/socket.ts
{
  type __IsExpected<Specific extends ApiRouteConfig> = Specific
  const handler = {} as typeof import("../../src/pages/api/socket.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/settings/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin/settings">> = Specific
  const handler = {} as typeof import("../../src/app/admin/settings/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/customer/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/customer">> = Specific
  const handler = {} as typeof import("../../src/app/customer/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/warehouse/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/warehouse">> = Specific
  const handler = {} as typeof import("../../src/app/warehouse/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
