// my-app/src/app/admin/invoices/generator/page.tsx
"use client";

import { useState, useEffect } from "react";
import { FileText, Plus, Trash2, Save, Download, User, Package, DollarSign, Calendar, Edit2, ArrowLeft } from "lucide-react";
import { ExportService } from "@/lib/export-service";
import toast, { Toaster } from "react-hot-toast";

type InvoiceItem = {
  id: string;
  description: string;
  quantity: number;
  unitPrice: number;
  total: number;
  packageId?: string;
  serviceType?: 'storage' | 'shipping' | 'customs' | 'delivery' | 'handling' | 'manual';
  trackingNumber?: string;
  autoGenerated?: boolean;
};

type CustomerPackage = {
  _id: string;
  trackingNumber: string;
  status: 'received' | 'in_transit' | 'delivered' | 'unknown';
  weight?: number;
  description?: string;
  createdAt: string;
  branch?: string;
  manifestId?: string;
  dimensions?: {
    length?: number;
    width?: number;
    height?: number;
    unit?: string;
    weight?: number;
    weightUnit?: string;
  };
};

type ServiceItem = {
  id: string;
  name: string;
  description: string;
  serviceType: 'storage' | 'shipping' | 'customs' | 'delivery' | 'handling';
  unitPrice: number;
  packageId: string;
  trackingNumber: string;
  justification: string;
  autoGenerated: boolean;
};

type Customer = {
  id: string;
  name: string;
  email: string;
  userCode: string;
  address?: string;
};

type CustomerApi = {
  _id?: string;
  id?: string;
  firstName?: string;
  lastName?: string;
  email?: string;
  userCode?: string;
  address?:
    | {
        street?: string;
        country?: string;
      }
    | string
    | null;
};

export default function InvoiceGeneratorPage() {
  const [customers, setCustomers] = useState<Customer[]>([]);
  const [selectedCustomer, setSelectedCustomer] = useState<Customer | null>(null);
  const [customerPackages, setCustomerPackages] = useState<CustomerPackage[]>([]);
  const [availableServices, setAvailableServices] = useState<ServiceItem[]>([]);
  const [servicesByPackage, setServicesByPackage] = useState<Record<string, ServiceItem[]>>({});
  const [selectedServices, setSelectedServices] = useState<string[]>([]);
  const [loadingPackages, setLoadingPackages] = useState(false);
  const [loadingServices, setLoadingServices] = useState(false);
  const [invoiceNumber, setInvoiceNumber] = useState("");
  const [issueDate, setIssueDate] = useState(new Date().toISOString().split('T')[0]);
  const [dueDate, setDueDate] = useState("");
  const [items, setItems] = useState<InvoiceItem[]>([]);
  const [notes, setNotes] = useState("");
  const [taxRate, setTaxRate] = useState(10);
  const [discount, setDiscount] = useState(0);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    loadCustomers();
    generateInvoiceNumber();
  }, []);

  async function loadCustomerPackages(customerId: string) {
    setLoadingPackages(true);
    try {
      // Find customer by ID to get userCode
      const customer = customers.find(c => c.id === customerId);
      if (!customer) {
        console.error("Customer not found:", customerId);
        return;
      }
      
      const res = await fetch(`/api/admin/packages?userCode=${customer.userCode}`, {
        credentials: 'include',
      });
      const data = await res.json();
      
      if (res.ok) {
        setCustomerPackages(data.packages || []);
        await generateServiceItems(data.packages || []);
      } else {
        console.error("Packages API error:", data);
        setCustomerPackages([]);
        setAvailableServices([]);
      }
    } catch (error) {
      console.error("Failed to load customer packages:", error);
      setCustomerPackages([]);
      setAvailableServices([]);
    } finally {
      setLoadingPackages(false);
    }
  }

  async function generateServiceItems(packages: CustomerPackage[]) {
    setLoadingServices(true);
    try {
      const services: ServiceItem[] = [];
      const servicesByPackage: Record<string, ServiceItem[]> = {};
      
      // Load custom services from settings
      const res = await fetch("/api/admin/services?isActive=true", {
        credentials: 'include',
      });
      const servicesData = await res.json();
      const customServices = servicesData.services || [];
      
      console.log('Loaded custom services:', customServices.length, 'services');
      
      // Only generate services from database if they exist
      if (customServices.length > 0) {
        for (const pkg of packages) {
          const daysInStorage = pkg.status === 'received' ? 
            Math.ceil((Date.now() - new Date(pkg.createdAt).getTime()) / (1000 * 60 * 60 * 24)) : 0;
          
          const packageServices: ServiceItem[] = [];
          
          // Generate services based on custom services configuration
          for (const service of customServices) {
            // Check if service conditions match this package
            let shouldApply = true;
            
            if (service.conditions) {
              // Check package status condition
              if (service.conditions.packageStatus && service.conditions.packageStatus.length > 0) {
                if (!service.conditions.packageStatus.includes(pkg.status)) {
                  shouldApply = false;
                }
              }
              
              // Check weight range condition
              if (service.conditions.weightRange && (service.conditions.weightRange.min || service.conditions.weightRange.max)) {
                const weight = pkg.weight || 0;
                if (service.conditions.weightRange.min && weight < service.conditions.weightRange.min) {
                  shouldApply = false;
                }
                if (service.conditions.weightRange.max && weight > service.conditions.weightRange.max) {
                  shouldApply = false;
                }
              }
              
              // Check branch condition
              if (service.conditions.branch && service.conditions.branch.length > 0) {
                if (!service.conditions.branch.includes(pkg.branch || '')) {
                  shouldApply = false;
                }
              }
              
              // Check days in storage condition
              if (service.conditions.daysInStorage && (service.conditions.daysInStorage.min || service.conditions.daysInStorage.max)) {
                if (service.conditions.daysInStorage.min && daysInStorage < service.conditions.daysInStorage.min) {
                  shouldApply = false;
                }
                if (service.conditions.daysInStorage.max && daysInStorage > service.conditions.daysInStorage.max) {
                  shouldApply = false;
                }
              }
            }
            
            if (shouldApply) {
              // Calculate price based on calculation method
              let calculatedPrice = service.unitPrice;
              
              switch (service.calculationMethod) {
                case 'per_kg':
                  calculatedPrice = service.unitPrice * (pkg.weight || 1);
                  break;
                case 'per_day':
                  calculatedPrice = service.unitPrice * daysInStorage;
                  break;
                case 'per_package':
                  calculatedPrice = service.unitPrice;
                  break;
                case 'fixed':
                default:
                  calculatedPrice = service.unitPrice;
                  break;
              }
              
              const serviceItem: ServiceItem = {
                id: `${service.serviceType}-${pkg._id}-${service._id}`,
                name: `${service.name}`,
                description: service.description,
                serviceType: service.serviceType,
                unitPrice: calculatedPrice,
                packageId: pkg._id,
                trackingNumber: pkg.trackingNumber,
                justification: `Service applied based on: ${pkg.status}, ${pkg.weight || 0}kg, ${pkg.branch || 'unknown branch'}`,
                autoGenerated: true,
              };
              
              services.push(serviceItem);
              packageServices.push(serviceItem);
            }
          }
          
          // Store services by package
          servicesByPackage[pkg._id] = packageServices;
        }
      } else {
        // No custom services found in database - show empty list
        console.log('No custom services found in database');
      }
      
      setAvailableServices(services);
      setServicesByPackage(servicesByPackage);
    } catch (error) {
      console.error("Failed to generate service items:", error);
    } finally {
      setLoadingServices(false);
    }
  }

  async function loadCustomers() {
    try {
      const res = await fetch("/api/admin/customers", {
        credentials: 'include',
      });
      const data = await res.json();
      
      if (!res.ok) {
        console.error("Failed to load customers:", data?.error);
        return;
      }
      const customerList = (Array.isArray(data?.items) ? data.items : []).map((c: CustomerApi) => {
        const id = String(c._id || c.id || '');
        const firstName = (c.firstName || '').trim();
        const lastName = (c.lastName || '').trim();
        const name = `${firstName} ${lastName}`.trim() || 'N/A';
        const email = c.email || '';
        const userCode = c.userCode || '';

        let address = '';
        if (typeof c.address === 'string') {
          address = c.address;
        } else if (c.address && typeof c.address === 'object') {
          address = `${c.address.street || ''}, ${c.address.country || ''}`.trim();
        }

        return {
          id,
          name,
          email,
          userCode,
          address,
        };
      });
      setCustomers(customerList);
    } catch (error) {
      console.error("Failed to load customers:", error);
    } finally {
      setLoadingServices(false);
    }
  }

  function generateInvoiceNumber() {
    const prefix = 'INV';
    const timestamp = Date.now().toString(36); // Base36 timestamp
    const randomChars = Math.random().toString(36).substring(2, 6).toUpperCase(); // 4 random chars
    const sequence = timestamp.slice(-4) + randomChars; // Combine for short unique ID
    setInvoiceNumber(`${prefix}-${sequence}`);
  }

  function addServiceToInvoice(serviceId: string) {
    const service = availableServices.find(s => s.id === serviceId);
    if (!service) return;
    
    // Check if service already added
    if (items.some(item => item.packageId === service.packageId && item.serviceType === service.serviceType)) {
      return;
    }
    
    const newItem: InvoiceItem = {
      id: service.id,
      description: service.description,
      quantity: 1,
      unitPrice: service.unitPrice,
      total: service.unitPrice,
      packageId: service.packageId,
      serviceType: service.serviceType,
      trackingNumber: service.trackingNumber,
      autoGenerated: true,
    };
    setItems([...items, newItem]);
    setSelectedServices([...selectedServices, serviceId]);
  }

  function removeServiceFromInvoice(serviceId: string) {
    setItems(items.filter(item => item.id !== serviceId));
    setSelectedServices(selectedServices.filter(id => id !== serviceId));
  }

  function updateItem(id: string, field: keyof InvoiceItem, value: string | number) {
    setItems(items.map(item => {
      if (item.id === id) {
        const updated = { ...item, [field]: value };
        if (field === 'quantity' || field === 'unitPrice') {
          updated.total = updated.quantity * updated.unitPrice;
        }
        return updated;
      }
      return item;
    }));
  }

  function removeItem(id: string) {
    setItems(items.filter(item => item.id !== id));
  }

  const subtotal = items.reduce((sum, item) => sum + item.total, 0);
  const discountAmount = (subtotal * discount) / 100;
  const taxableAmount = subtotal - discountAmount;
  const taxAmount = (taxableAmount * taxRate) / 100;
  const total = taxableAmount + taxAmount;

  async function saveInvoice() {
    if (!selectedCustomer) {
      alert("Please select a customer");
      return;
    }
    if (items.length === 0) {
      alert("Please add at least one item");
      return;
    }
    const hasEmptyDescription = items.some((item) => !item.description || item.description.trim().length === 0);
    if (hasEmptyDescription) {
      alert("Please fill in a description for each item");
      return;
    }

    setLoading(true);
    try {
      // Map to main Invoice model shape so records appear on /admin/invoices
      const payload = {
        customer: {
          id: selectedCustomer.id,
          name: selectedCustomer.name,
          email: selectedCustomer.email,
          address: selectedCustomer.address || "N/A",
          city: "N/A",
          country: "N/A",
        },
        items: items.map((item) => ({
          description: item.description,
          quantity: item.quantity,
          unitPrice: item.unitPrice,
          taxRate: taxRate,
          amount: 0,
          taxAmount: 0,
          total: 0,
        })),
        status: "draft",
        issueDate: new Date(issueDate),
        dueDate: dueDate ? new Date(dueDate) : undefined,
        paymentTerms: 30,
        currency: "JMD",
        amountPaid: 0,
        notes,
      };

      const res = await fetch("/api/admin/invoices", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        credentials: 'include',
        body: JSON.stringify(payload),
      });
      
      if (!res.ok) {
        let message = "Failed to save invoice";
        try {
          const errorBody = await res.json();
          if (errorBody?.error) {
            message = typeof errorBody.error === "string" ? errorBody.error : JSON.stringify(errorBody.error);
          }
        } catch {
          // ignore JSON parse errors
        }
        throw new Error(message);
      }

      await res.json();
      toast.success("Invoice saved successfully!", {
        duration: 4000,
        icon: "✅",
        style: {
          background: "#10b981",
          color: "#fff",
          padding: "16px",
          borderRadius: "8px",
          fontSize: "14px",
          fontWeight: "500",
        },
      });
      resetForm();
    } catch (error) {
      console.error("Save invoice error:", error);
      const errorMessage = error instanceof Error ? error.message : "Failed to save invoice";
      toast.error(errorMessage, {
        duration: 5000,
        icon: "❌",
        style: {
          background: "#ef4444",
          color: "#fff",
          padding: "16px",
          borderRadius: "8px",
          fontSize: "14px",
          fontWeight: "500",
        },
      });
    } finally {
      setLoading(false);
    }
  }

  async function exportInvoice(format: 'pdf' | 'excel') {
    if (!selectedCustomer) {
      alert("Please select a customer");
      return;
    }

    if (format === 'excel') {
      // Enhanced invoice data with complete details
      const invoiceData = {
        'Invoice Number': invoiceNumber,
        'Customer Name': selectedCustomer.name,
        'Customer Email': selectedCustomer.email,
        'Customer Address': selectedCustomer.address || "N/A",
        'Customer ID': selectedCustomer.id,
        'Issue Date': issueDate,
        'Due Date': dueDate,
        'Subtotal': subtotal.toFixed(2),
        'Discount': `${discount}% ($${discountAmount.toFixed(2)})`,
        'Tax': `${taxRate}% ($${taxAmount.toFixed(2)})`,
        'Total': total.toFixed(2),
        'Currency': 'JMD',
        'Status': 'Draft',
        'Payment Terms': '30 days',
        'Notes': notes || 'N/A'
      };

      // Enhanced items data with complete details
      const itemsData = items.map((item, index) => ({
        'Item #': index + 1,
        'Description': item.description,
        'Quantity': item.quantity,
        'Unit Price': `$${item.unitPrice.toFixed(2)}`,
        'Tax Rate': `${taxRate}%`,
        'Tax Amount': `$${(item.unitPrice * item.quantity * taxRate / 100).toFixed(2)}`,
        'Line Total': `$${item.total.toFixed(2)}`,
        'Service Type': item.serviceType || 'manual',
        'Package Related': item.trackingNumber || 'N/A',
        'Auto-Generated': item.autoGenerated ? 'Yes' : 'No',
        'Package ID': item.packageId || 'N/A'
      }));

      // Customer details sheet
      const customerData = [{
        'Customer Name': selectedCustomer.name,
        'Customer Email': selectedCustomer.email,
        'Customer Address': selectedCustomer.address || 'N/A',
        'Customer ID': selectedCustomer.id,
        'Customer Code': selectedCustomer.userCode || 'N/A'
      }];

      // Package details sheet (for packages related to invoice items)
      const packageData = items
        .filter(item => item.packageId && item.trackingNumber)
        .map(item => ({
          'Package ID': item.packageId,
          'Tracking Number': item.trackingNumber,
          'Service Type': item.serviceType,
          'Related Item': item.description,
          'Invoice': invoiceNumber
        }));

      // Financial summary sheet
      const financialData = [{
        'Invoice Number': invoiceNumber,
        'Subtotal': subtotal.toFixed(2),
        'Discount Amount': discountAmount.toFixed(2),
        'Tax Amount': taxAmount.toFixed(2),
        'Total Amount': total.toFixed(2),
        'Tax Rate': `${taxRate}%`,
        'Discount Rate': `${discount}%`,
        'Currency': 'JMD',
        'Payment Terms': '30 days',
        'Status': 'Draft'
      }];

      // Export multiple sheets with comprehensive data
      ExportService.toExcelMultiSheet([
        { name: 'Invoice Summary', data: [invoiceData] },
        { name: 'Invoice Items', data: itemsData },
        { name: 'Customer Details', data: customerData },
        { name: 'Financial Summary', data: financialData },
        ...(packageData.length > 0 ? [{ name: 'Package Details', data: packageData }] : [])
      ], `invoice_${invoiceNumber}_complete`);
    } else if (format === 'pdf') {
      // PDF export using the same invoice structure
      const invoiceForPDF = {
        invoiceNumber,
        customer: {
          name: selectedCustomer.name,
          email: selectedCustomer.email,
          address: selectedCustomer.address,
          id: selectedCustomer.id
        },
        issueDate,
        dueDate,
        status: 'draft',
        currency: 'JMD',
        total,
        amountPaid: 0,
        balanceDue: total,
        items,
        notes,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
      };

      await ExportService.toInvoicePDF(invoiceForPDF, `invoice_${invoiceNumber}`);
    }
  }

  function resetForm() {
    setSelectedCustomer(null);
    generateInvoiceNumber();
    setIssueDate(new Date().toISOString().split('T')[0]);
    setDueDate("");
    setItems([]);
    setNotes("");
    setDiscount(0);
  }

  return (
    <>
      <Toaster 
        position="top-right"
        reverseOrder={false}
        gutter={8}
        containerClassName=""
        containerStyle={{}}
        toastOptions={{
          duration: 4000,
          style: {
            background: "#363636",
            color: "#fff",
          },
          success: {
            duration: 4000,
            iconTheme: {
              primary: "#10b981",
              secondary: "#fff",
            },
          },
          error: {
            duration: 5000,
            iconTheme: {
              primary: "#ef4444",
              secondary: "#fff",
            },
          },
        }}
      />
      <div className="min-h-screen bg-gradient-to-br from-gray-50 via-blue-50/30 to-orange-50/20 p-4 md:p-6 lg:p-8">
        <div className="max-w-7xl mx-auto space-y-6">
          {/* Header Section */}
          <header className="relative overflow-hidden rounded-3xl border border-white/50 bg-gradient-to-r from-[#0f4d8a] via-[#0e447d] to-[#0d3d70] p-6 text-white shadow-2xl mb-8">
            <div className="absolute inset-0 bg-white/10" />
            <div className="relative flex flex-col gap-6">
              <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
                <div className="flex items-center gap-4">
                  <div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-white/15 backdrop-blur">
                    <FileText className="h-7 w-7" />
                  </div>
                  <div>
                    <p className="text-sm uppercase tracking-widest text-blue-100">Invoice Generator</p>
                    <h1 className="text-3xl font-bold leading-tight md:text-4xl">Create Invoice</h1>
                    <p className="text-blue-100 mt-1">Generate professional invoices for customer payments and record-keeping</p>
                  </div>
                </div>
                <a 
                    href="/admin/invoices" 
                    className="flex items-center gap-2 px-4 py-2 bg-white/15 backdrop-blur rounded-lg hover:bg-white/25 transition-colors"
                  >
                    <ArrowLeft className="w-4 h-4" />
                    Back to Invoices
                  </a>
              </div>
            </div>
          </header>

          {/* Main Form */}
          <div className="bg-white rounded-2xl shadow-xl border border-gray-200 overflow-hidden">
            <div className="bg-gradient-to-r from-[#0891b2] to-[#06b6d4] px-6 py-4">
              <h2 className="text-xl font-semibold text-white">Invoice #{invoiceNumber}</h2>
            </div>
            <div className="p-6 space-y-6">
              {/* Customer and Dates Section */}
              <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                <div className="md:col-span-2">
                  <label className="block text-sm font-medium text-slate-700 mb-2">
                    <User className="inline w-4 h-4 mr-1" />
                    Select Customer *
                  </label>
                  <select
                    value={selectedCustomer?.id || ""}
                    onChange={(e) => {
                      const customer = customers.find(c => c.id === e.target.value);
                      setSelectedCustomer(customer || null);
                      if (customer) {
                        loadCustomerPackages(customer.id);
                      } else {
                        setCustomerPackages([]);
                        setAvailableServices([]);
                        setServicesByPackage({});
                        setSelectedServices([]);
                      }
                    }}
                    className="w-full rounded-lg border-2 border-slate-200 px-4 py-3 focus:border-[#0f4d8a] focus:outline-none focus:ring-2 focus:ring-[#0f4d8a]/20"
                    required
                  >
                    <option value="">Choose a customer...</option>
                    {customers.map(customer => (
                      <option key={customer.id} value={customer.id}>
                        {customer.name} ({customer.userCode})
                      </option>
                    ))}
                  </select>
                  {selectedCustomer && (
                    <div className="mt-2 p-3 bg-slate-50 rounded-lg text-sm">
                      <p className="text-slate-700">📧 {selectedCustomer.email}</p>
                      {selectedCustomer.address && (
                        <p className="text-slate-600 mt-1">📍 {selectedCustomer.address}</p>
                      )}
                    </div>
                  )}
                </div>

                <div className="space-y-4">
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-2">
                      <Calendar className="inline w-4 h-4 mr-1" />
                      Issue Date *
                    </label>
                    <input
                      type="date"
                      value={issueDate}
                      onChange={(e) => setIssueDate(e.target.value)}
                      className="w-full rounded-lg border-2 border-slate-200 px-4 py-3 focus:border-[#0f4d8a] focus:outline-none focus:ring-2 focus:ring-[#0f4d8a]/20"
                      required
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-2">
                      Due Date
                    </label>
                    <input
                      type="date"
                      value={dueDate}
                      onChange={(e) => setDueDate(e.target.value)}
                      className="w-full rounded-lg border-2 border-slate-200 px-4 py-3 focus:border-[#0f4d8a] focus:outline-none focus:ring-2 focus:ring-[#0f4d8a]/20"
                    />
                  </div>
                </div>
              </div>

              {/* Customer Packages and Services Section */}
              {selectedCustomer && (
                <div className="space-y-6">
                  {/* Customer Packages Overview */}
                  <div className="bg-white rounded-2xl shadow-lg border border-gray-200 overflow-hidden">
                    <div className="bg-gradient-to-r from-blue-500 to-blue-600 px-6 py-4">
                      <h3 className="text-lg font-semibold text-white flex items-center gap-2">
                        <Package className="w-5 h-5" />
                        Customer Packages - {customerPackages.length} Found
                      </h3>
                    </div>
                    <div className="p-6">
                      {loadingPackages ? (
                        <div className="flex items-center justify-center py-8">
                          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-500"></div>
                        </div>
                      ) : customerPackages.length === 0 ? (
                        <div className="text-center py-8 text-gray-500">
                          <Package className="w-12 h-12 mx-auto mb-2 text-gray-300" />
                          <p>No packages found for this customer</p>
                          <p className="text-sm mt-1">Only manual services can be added to this invoice</p>
                        </div>
                      ) : (
                        <div className="space-y-3">
                          {customerPackages.map((pkg) => (
                            <div key={pkg._id} className="flex items-center justify-between p-4 bg-gray-50 rounded-lg border border-gray-200">
                              <div className="flex items-center gap-4">
                                <div className="flex items-center justify-center w-10 h-10 rounded-full bg-blue-100 text-blue-600 font-bold">
                                  {pkg.trackingNumber.slice(-4)}
                                </div>
                                <div>
                                  <p className="font-semibold text-gray-800">{pkg.trackingNumber}</p>
                                  <p className="text-sm text-gray-600">{pkg.description || 'No description'}</p>
                                  <div className="flex items-center gap-4 mt-1 text-xs text-gray-500">
                                    <span>Weight: {pkg.weight || 0}kg</span>
                                    <span>Status: <span className={`px-2 py-1 rounded-full text-xs ${
                                      pkg.status === 'delivered' ? 'bg-green-100 text-green-700' :
                                      pkg.status === 'in_transit' ? 'bg-blue-100 text-blue-700' :
                                      pkg.status === 'received' ? 'bg-yellow-100 text-yellow-700' :
                                      'bg-gray-100 text-gray-700'
                                    }`}>{pkg.status}</span></span>
                                    <span>Created: {new Date(pkg.createdAt).toLocaleDateString()}</span>
                                  </div>
                                </div>
                              </div>
                            </div>
                          ))}
                        </div>
                      )}
                    </div>
                  </div>

                  {/* Available Services - Grouped by Package */}
                  {customerPackages.length > 0 && Object.keys(servicesByPackage).length > 0 ? (
                    <div className="space-y-6">
                      {customerPackages.map((pkg) => {
                        const packageServices = servicesByPackage[pkg._id] || [];
                        const hasServicesInInvoice = items.some(item => item.packageId === pkg._id);
                        
                        return (
                          <div key={pkg._id} className="bg-white rounded-2xl shadow-lg border border-gray-200 overflow-hidden">
                            <div className="bg-gradient-to-r from-indigo-500 to-indigo-600 px-6 py-4">
                              <div className="flex items-center justify-between">
                                <div className="flex items-center gap-3">
                                  <Package className="w-5 h-5" />
                                  <div>
                                    <h3 className="text-lg font-semibold text-white">
                                      {pkg.trackingNumber} - Available Services
                                    </h3>
                                    <p className="text-indigo-100 text-sm mt-1">
                                      {packageServices.length} services available • {pkg.weight || 0}kg • {pkg.status}
                                    </p>
                                  </div>
                                </div>
                                {hasServicesInInvoice && (
                                  <button
                                    className="flex items-center gap-2 px-4 py-2 bg-white/20 text-white rounded-lg hover:bg-white/30 transition-colors"
                                    onClick={() => {
                                      // Remove all services for this package from invoice
                                      const packageItems = items.filter(item => item.packageId === pkg._id);
                                      packageItems.forEach(item => removeServiceFromInvoice(item.id));
                                    }}
                                  >
                                    <Edit2 className="w-4 h-4" />
                                    Edit Package
                                  </button>
                                )}
                              </div>
                            </div>
                            <div className="p-6">
                              {packageServices.length === 0 ? (
                                <div className="text-center py-8">
                                  <Package className="w-12 h-12 text-gray-300 mx-auto mb-3" />
                                  <p className="text-gray-500 font-medium">No services available for this package</p>
                                  <p className="text-sm text-gray-400 mt-1">
                                    This package doesn&apos;t match any service conditions
                                  </p>
                                </div>
                              ) : (
                                <div className="space-y-3">
                                  {packageServices.map((service) => {
                                    const isInInvoice = items.some(item => item.id === service.id);
                                    return (
                                      <div key={service.id} className={`border rounded-lg p-4 transition-all ${
                                        isInInvoice ? 'border-green-500 bg-green-50' : 'border-gray-200 bg-gray-50'
                                      }`}>
                                        <div className="flex items-center justify-between">
                                          <div className="flex-1">
                                            <div className="flex items-center gap-3 mb-2">
                                              <h4 className="font-semibold text-gray-800">{service.name}</h4>
                                              <span className={`px-2 py-1 rounded-full text-xs font-medium ${
                                                service.serviceType === 'storage' ? 'bg-blue-100 text-blue-700' :
                                                service.serviceType === 'handling' ? 'bg-yellow-100 text-yellow-700' :
                                                service.serviceType === 'customs' ? 'bg-purple-100 text-purple-700' :
                                                service.serviceType === 'delivery' ? 'bg-green-100 text-green-700' :
                                                'bg-gray-100 text-gray-700'
                                              }`}>{service.serviceType}</span>
                                              {service.autoGenerated && (
                                                <span className="px-2 py-1 rounded-full text-xs bg-orange-100 text-orange-700">
                                                  Auto-generated
                                                </span>
                                              )}
                                            </div>
                                            <p className="text-sm text-gray-600 mb-2">{service.description}</p>
                                            <p className="text-xs text-gray-500 italic mb-2">
                                              <strong>Justification:</strong> {service.justification}
                                            </p>
                                            <div className="flex items-center gap-4 text-sm">
                                              <span className="font-bold text-lg text-green-600">${service.unitPrice.toFixed(2)}</span>
                                              <span className="text-gray-500">Package: {pkg.trackingNumber}</span>
                                            </div>
                                          </div>
                                          <div className="flex items-center gap-2">
                                            {isInInvoice ? (
                                              <div className="flex items-center gap-2 text-green-600">
                                                <span className="text-sm font-medium">Added</span>
                                                <button
                                                  onClick={() => removeServiceFromInvoice(service.id)}
                                                  className="p-2 rounded-lg text-red-600 hover:bg-red-50 transition-colors"
                                                  title="Remove from invoice"
                                                >
                                                  <Trash2 className="w-4 h-4" />
                                                </button>
                                              </div>
                                            ) : (
                                              <button
                                                onClick={() => addServiceToInvoice(service.id)}
                                                className="flex items-center gap-2 px-4 py-2 rounded-lg bg-green-500 text-white font-medium hover:bg-green-600 transition-colors"
                                              >
                                                <Plus className="w-4 h-4" />
                                                Add to Invoice
                                              </button>
                                            )}
                                          </div>
                                        </div>
                                      </div>
                                    );
                                  })}
                                </div>
                              )}
                            </div>
                          </div>
                        );
                      })}
                    </div>
                  ) : (
                    !loadingServices && (
                      <div className="bg-white rounded-2xl shadow-lg border border-gray-200 overflow-hidden">
                        <div className="bg-gradient-to-r from-orange-500 to-orange-600 px-6 py-4">
                          <h3 className="text-lg font-semibold text-white flex items-center gap-2">
                            <DollarSign className="w-5 h-5" />
                            No Services Available
                          </h3>
                          <p className="text-orange-100 text-sm mt-1">Services from database not found</p>
                        </div>
                        <div className="p-6">
                          <div className="text-center py-8">
                            <div className="mb-4">
                              <div className="mx-auto w-16 h-16 bg-orange-100 rounded-full flex items-center justify-center">
                                <DollarSign className="w-8 h-8 text-orange-600" />
                              </div>
                            </div>
                            <h4 className="text-lg font-semibold text-gray-800 mb-2">No Database Services Found</h4>
                            <p className="text-gray-600 mb-4">
                              No services were found in your database. Please add services in Admin Settings first.
                            </p>
                            <div className="space-y-2">
                              <a 
                                href="/admin/settings" 
                                className="inline-flex items-center gap-2 px-4 py-2 bg-orange-500 text-white rounded-lg hover:bg-orange-600 transition-colors"
                              >
                                <DollarSign className="w-4 h-4" />
                                Go to Settings to Add Services
                              </a>
                              <div className="text-sm text-gray-500">
                                Or use manual invoice items below
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    )
                  )}
                </div>
              )}

              {/* Items Section */}
              <div>
                <div className="flex items-center justify-between mb-4">
                  <h3 className="text-lg font-semibold text-slate-800 flex items-center gap-2">
                    <Package className="w-5 h-5" />
                    Line Items
                  </h3>
                  <a 
                    href="/admin/settings"
                    className="flex items-center gap-2 px-4 py-2 rounded-lg bg-[#E67919] text-white font-medium hover:bg-[#d66f15] transition-colors"
                  >
                    <Plus className="w-4 h-4" />
                    Add Services
                  </a>
                </div>

                <div className="space-y-3">
                  {items.map((item, index) => (
                    <div key={item.id} className="flex gap-3 items-start p-4 bg-slate-50 rounded-lg">
                      <span className="flex items-center justify-center w-8 h-8 rounded-full bg-[#0f4d8a] text-white font-bold text-sm">
                        {index + 1}
                      </span>
                      <div className="flex-1 grid grid-cols-1 md:grid-cols-4 gap-3">
                        <input
                          type="text"
                          placeholder="Item description"
                          value={item.description}
                          onChange={(e) => updateItem(item.id, 'description', e.target.value)}
                          className="md:col-span-2 rounded-lg border border-slate-300 px-3 py-2 focus:border-[#0f4d8a] focus:outline-none"
                        />
                        <input
                          type="number"
                          placeholder="Qty"
                          min="1"
                          value={item.quantity}
                          onChange={(e) => updateItem(item.id, 'quantity', Number(e.target.value))}
                          className="rounded-lg border border-slate-300 px-3 py-2 focus:border-[#0f4d8a] focus:outline-none"
                        />
                        <input
                          type="number"
                          placeholder="Unit Price"
                          min="0"
                          step="0.01"
                          value={item.unitPrice}
                          onChange={(e) => updateItem(item.id, 'unitPrice', Number(e.target.value))}
                          className="rounded-lg border border-slate-300 px-3 py-2 focus:border-[#0f4d8a] focus:outline-none"
                        />
                      </div>
                      <div className="flex items-center gap-2">
                        <span className="font-bold text-slate-800 min-w-[80px] text-right">
                          ${item.total.toFixed(2)}
                        </span>
                        <button
                          onClick={() => removeItem(item.id)}
                          className="p-2 rounded-lg text-red-600 hover:bg-red-50 transition-colors"
                        >
                          <Trash2 className="w-4 h-4" />
                        </button>
                      </div>
                    </div>
                  ))}
                  {items.length === 0 && (
                    <div className="text-center py-8 text-slate-500">
                      <Package className="w-12 h-12 mx-auto mb-2 text-slate-300" />
                      <p>No items added yet. Click &quot;Add Services&quot; to start.</p>
                    </div>
                  )}
                </div>
              </div>

              {/* Calculations */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="space-y-4">
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-2">
                      Discount (%)
                    </label>
                    <input
                      type="number"
                      min="0"
                      max="100"
                      value={discount}
                      onChange={(e) => setDiscount(Number(e.target.value))}
                      className="w-full rounded-lg border-2 border-slate-200 px-4 py-2 focus:border-[#0f4d8a] focus:outline-none"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-2">
                      Tax Rate (%)
                    </label>
                    <input
                      type="number"
                      min="0"
                      value={taxRate}
                      onChange={(e) => setTaxRate(Number(e.target.value))}
                      className="w-full rounded-lg border-2 border-slate-200 px-4 py-2 focus:border-[#0f4d8a] focus:outline-none"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-2">
                      Notes
                    </label>
                    <textarea
                      value={notes}
                      onChange={(e) => setNotes(e.target.value)}
                      rows={4}
                      className="w-full rounded-lg border-2 border-slate-200 px-4 py-2 focus:border-[#0f4d8a] focus:outline-none resize-none"
                      placeholder="Add any additional notes..."
                    />
                  </div>
                </div>

                <div className="bg-gradient-to-br from-slate-50 to-white rounded-xl p-6 border-2 border-slate-200">
                  <h3 className="text-lg font-semibold text-slate-800 mb-4 flex items-center gap-2">
                    <DollarSign className="w-5 h-5" />
                    Invoice Summary
                  </h3>
                  <div className="space-y-3">
                    <div className="flex justify-between text-slate-700">
                      <span>Subtotal:</span>
                      <span className="font-semibold">${subtotal.toFixed(2)}</span>
                    </div>
                    {discount > 0 && (
                      <div className="flex justify-between text-green-600">
                        <span>Discount ({discount}%):</span>
                        <span className="font-semibold">-${discountAmount.toFixed(2)}</span>
                      </div>
                    )}
                    <div className="flex justify-between text-slate-700">
                      <span>Tax ({taxRate}%):</span>
                      <span className="font-semibold">${taxAmount.toFixed(2)}</span>
                    </div>
                    <div className="border-t-2 border-slate-300 pt-3 flex justify-between items-center">
                      <span className="text-lg font-bold text-slate-900">Total:</span>
                      <span className="text-2xl font-bold text-[#0f4d8a]">${total.toFixed(2)}</span>
                    </div>
                  </div>
                </div>
              </div>

              {/* Action Buttons */}
              <div className="flex flex-wrap gap-3 pt-4 border-t border-slate-200">
                <button
                  onClick={saveInvoice}
                  disabled={loading || !selectedCustomer || items.length === 0}
                  className="flex items-center gap-2 px-6 py-3 rounded-lg bg-gradient-to-r from-[#0f4d8a] to-[#E67919] text-white font-medium hover:shadow-lg transition-all disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  <Save className="w-4 h-4" />
                  {loading ? 'Saving...' : 'Save Invoice'}
                </button>
                
                <button
                  onClick={() => exportInvoice('excel')}
                  disabled={!selectedCustomer || items.length === 0}
                  className="flex items-center gap-2 px-6 py-3 rounded-lg border-2 border-[#0f4d8a] text-[#0f4d8a] font-medium hover:bg-[#0f4d8a] hover:text-white transition-all disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  <Download className="w-4 h-4" />
                  Export Excel
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}